title:              Naochanâ€™s Blog
description:        Naochan Official Blog
author:             naochan83275
url:                "https://naochan83275.github.io"
baseurl:            "/blog"
copyright:          "&copy; 2024 Naochan83275"

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
collections:
  authors:
    output: true
